/**
 * ApplyRN user relevance profile (PRD 5.x, revised for V0 acceptance).
 *
 * This is the single source of truth for the user's job-search scope:
 * - Geography: US only (remote-US or in-person-US).
 * - Level: early-career only (internships, co-ops, apprenticeship, new grad,
 *   early career, work study, entry level).
 * - Role family: software + data + ML engineering-track. Everything else
 *   (sales, marketing, design, product management, recruiting, operations,
 *   customer success, etc.) is excluded.
 *
 * The profile is plain data so it can later live in config/private/ and be
 * seeded to D1 like the watchlist; the package default mirrors the user's
 * stated scope so the engine is deterministic and testable without config.
 */

/** Geographic signals. */
export const US_STATES_AND_TERRITORIES = [
  "alaska",
  "alabama",
  "arkansas",
  "american samoa",
  "arizona",
  "california",
  "colorado",
  "connecticut",
  "district of columbia",
  "delaware",
  "florida",
  "georgia",
  "guam",
  "hawaii",
  "iowa",
  "idaho",
  "illinois",
  "indiana",
  "kansas",
  "kentucky",
  "louisiana",
  "massachusetts",
  "maryland",
  "maine",
  "michigan",
  "minnesota",
  "missouri",
  "mississippi",
  "montana",
  "north carolina",
  "north dakota",
  "nebraska",
  "new hampshire",
  "new jersey",
  "new mexico",
  "nevada",
  "new york",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "puerto rico",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "virginia",
  "virgin islands",
  "vermont",
  "washington",
  "wisconsin",
  "west virginia",
  "wyoming",
] as const;

/** Two-letter state/territory codes (word-boundary matched). */
export const US_STATE_CODES = [
  "AK",
  "AL",
  "AR",
  "AS",
  "AZ",
  "CA",
  "CO",
  "CT",
  "DC",
  "DE",
  "FL",
  "GA",
  "GU",
  "HI",
  "IA",
  "ID",
  "IL",
  "IN",
  "KS",
  "KY",
  "LA",
  "MA",
  "MD",
  "ME",
  "MI",
  "MN",
  "MO",
  "MP",
  "MS",
  "MT",
  "NC",
  "ND",
  "NE",
  "NH",
  "NJ",
  "NM",
  "NV",
  "NY",
  "OH",
  "OK",
  "OR",
  "PA",
  "PR",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VA",
  "VI",
  "VT",
  "WA",
  "WI",
  "WV",
  "WY",
] as const;

/**
 * Countries/regions OUTSIDE the US. Any of these appearing in a location
 * string (word boundary) marks the role as non-US. Deliberately not
 * exhaustive of the whole planet — it covers the countries the user flagged
 * (UK, Germany, Japan, France, Denmark, Spain, Singapore, Ireland) plus the
 * common international remote hubs.
 */
export const NON_US_REGIONS = [
  "uk",
  "united kingdom",
  "england",
  "scotland",
  "wales",
  "britain",
  "london",
  "manchester",
  "birmingham",
  "edinburgh",
  "germany",
  "berlin",
  "munich",
  "hamburg",
  "frankfurt",
  "cologne",
  "france",
  "paris",
  "lyon",
  "denmark",
  "copenhagen",
  "netherlands",
  "amsterdam",
  "rotterdam",
  "belgium",
  "brussels",
  "switzerland",
  "zurich",
  "austria",
  "vienna",
  "sweden",
  "stockholm",
  "norway",
  "oslo",
  "finland",
  "helsinki",
  "finland",
  "ireland",
  "dublin",
  "cork",
  "spain",
  "madrid",
  "barcelona",
  "portugal",
  "lisbon",
  "italy",
  "milan",
  "italy",
  "japan",
  "tokyo",
  "osaka",
  "kyoto",
  "singapore",
  "hong kong",
  "china",
  "beijing",
  "shanghai",
  "shenzhen",
  "taiwan",
  "taipei",
  "south korea",
  "seoul",
  "india",
  "bengaluru",
  "bangalore",
  "mumbai",
  "delhi",
  "canada",
  "toronto",
  "vancouver",
  "montreal",
  "australia",
  "sydney",
  "melbourne",
  "brisbane",
  "new zealand",
  "auckland",
  "israel",
  "tel aviv",
  "dubai",
  "poland",
  "warsaw",
  "krakow",
  "czech",
  "prague",
  "romania",
  "bulgaria",
  "greece",
  "athens",
  "south america",
  "brazil",
  "sao paulo",
  "mexico",
  "mexico city",
  "argentina",
  "buenos aires",
  "africa",
  "nigeria",
  "kenya",
  "egypt",
  "south africa",
  "capetown",
  "middle east",
  "saudi arabia",
  "united arab emirates",
  "uae",
  "qatar",
  "india",
] as const;

/**
 * Early-career markers. A title must contain at least one of these for the
 * role to be in scope (matches the user's stated scope: internships,
 * co-ops, apprenticeships, work study, new grad, early career).
 */
export const EARLY_CAREER_MARKERS = [
  "intern",
  "internship",
  "co-op",
  "coop",
  "apprentice",
  "apprenticeship",
  "work study",
  "work-study",
  "new grad",
  "new graduate",
  "early career",
  "entry level",
  "entry-level",
  "graduate",
  "university",
  "undergrad",
  "fresh grad",
  "campus",
  "summer associate",
  "junior",
  "jr.",
  "new hire",
  "student",
  "recent grad",
] as const;

/**
 * Seniority / leadership markers that put a role out of early-career scope.
 * Matched on the TITLE only (prose mentioning senior people inside the
 * description must never suppress an internship).
 */
export const SENIORITY_MARKERS = [
  "senior",
  "sr.",
  "staff",
  "principal",
  "lead",
  "manager",
  "director",
  "vp",
  "vice president",
  "head of",
  "head",
  "architect",
  "distinguished",
  "fellow",
  "expert",
  "experienced",
  "ii",
  "iii",
  "iv",
  "v",
  "senior staff",
] as const;

/** Software / data / ML engineering-track role families (positive gate). */
export const ENGINEERING_TRACK_MARKERS = [
  // core SWE
  "software",
  "swe",
  "developer",
  "programmer",
  "engineer",
  "engineering",
  // web / application layers
  "backend",
  "back end",
  "frontend",
  "front end",
  "full-stack",
  "fullstack",
  // data + ML + applied AI
  "data",
  "ml",
  "machine learning",
  "ai",
  "artificial intelligence",
  "nlp",
  // infra / platform / ops
  "infrastructure",
  "infra",
  "platform",
  "systems",
  "sre",
  "devops",
  "cloud",
  // embedded / low-level
  "embedded",
  "firmware",
  // test / automation / reliability of software itself
  "test",
  "testing",
  "qa",
  "quality assurance",
  "automation",
  // developer tooling
  "developer tools",
  "devtools",
  // specialized engineering
  "research engineer",
  "security engineer",
  "quant",
] as const;

/**
 * Explicitly non-software role families. These WIN over engineering-track
 * markers: the user's scope is software + data + ML only, so a "Sales
 * Engineer", "Design Engineer", or "Legal Ops Engineer" is out of scope even
 * though "engineer" appears in the title.
 */
export const NON_ENGINEERING_ROLE_MARKERS = [
  "sales",
  "account executive",
  "account manager",
  "business development",
  "bd",
  "sdr",
  "bdr",
  "marketing",
  "content",
  "brand",
  "growth",
  "seo",
  "design",
  "designer",
  "ux",
  "ui",
  "product designer",
  "product manager",
  "product management",
  "pm",
  "program manager",
  "project manager",
  "recruiter",
  "recruiting",
  "talent",
  "people ops",
  "hr",
  "human resources",
  "operations",
  "ops",
  "compliance",
  "grc",
  "governance",
  "risk",
  "legal",
  "law",
  "paralegal",
  "finance",
  "accounting",
  "controller",
  "customer success",
  "customer support",
  "support engineer (non-technical)",
  "client success",
  "community",
  "social media",
  "coordinator",
  "operations associate",
  "implementation",
  "onboarding",
  "solutions consultant",
  "analyst",
  "accountant",
  "auditor",
  "business analyst",
  "data analyst (non-eng)",
  "technical writer",
  "writer",
  "editor",
  "teacher",
  "instructor",
  "administrative",
  "executive assistant",
  "office manager",
  "receptionist",
] as const;

/** Skills used to differentiate score (title matches weigh more). */
export const TITLE_STRONG_SKILLS = [
  "python",
  "golang",
  "go",
  "rust",
  "c++",
  "cpp",
  "c#",
  "java",
  "typescript",
  "javascript",
  "react",
  "node",
  "sql",
  "postgres",
  "kubernetes",
  "docker",
  "aws",
  "gcp",
  "azure",
  "pytorch",
  "tensorflow",
  "llm",
  "large language model",
  "genai",
  "rag",
  "distributed",
  "pipeline",
  "etl",
  "data analysis",
] as const;

export const DESCRIPTION_STRONG_SKILLS = [
  "python",
  "golang",
  "rust",
  "c++",
  "java",
  "typescript",
  "javascript",
  "pytorch",
  "tensorflow",
  "kubernetes",
  "docker",
  "postgres",
  "sql",
  "aws",
  "gcp",
  "azure",
  "llm",
  "rag",
  "distributed systems",
  "etl",
] as const;

export interface RelevanceProfile {
  /** Role must be in at least one of these countries (default: US only). */
  allowedCountries: string[];
  /**
   * Minimum explained fit for a within-scope role to be considered alertable.
   * Defaults low (any within-scope role alerts per PRD "ranks don't gate");
   * hard gates already suppress out-of-scope noise.
   */
  alertThreshold: number;
}
