/**
 * ApplyRN user relevance profile (PRD 5.x, revised for V0 acceptance).
 *
 * This is the single source of truth for the user's job-search scope:
 * - Geography: US only (remote-US or in-person-US).
 * - Level: early-career only (internships, co-ops, apprenticeship, new grad,
 *   early career, work study, entry level).
 * - Role family: software + data + ML engineering-track. Everything else
 *   (sales, marketing, design, product management, recruiting, operations,
 *   customer success, etc.) is excluded.
 *
 * The profile is plain data so it can later live in config/private/ and be
 * seeded to D1 like the watchlist; the package default mirrors the user's
 * stated scope so the engine is deterministic and testable without config.
 */

/** Geographic signals. */
export const US_STATES_AND_TERRITORIES = [
  "alaska",
  "alabama",
  "arkansas",
  "american samoa",
  "arizona",
  "california",
  "colorado",
  "connecticut",
  "district of columbia",
  "delaware",
  "florida",
  "georgia",
  "guam",
  "hawaii",
  "iowa",
  "idaho",
  "illinois",
  "indiana",
  "kansas",
  "kentucky",
  "louisiana",
  "massachusetts",
  "maryland",
  "maine",
  "michigan",
  "minnesota",
  "missouri",
  "mississippi",
  "montana",
  "north carolina",
  "north dakota",
  "nebraska",
  "new hampshire",
  "new jersey",
  "new mexico",
  "nevada",
  "new york",
  "ohio",
  "oklahoma",
  "oregon",
  "pennsylvania",
  "puerto rico",
  "rhode island",
  "south carolina",
  "south dakota",
  "tennessee",
  "texas",
  "utah",
  "virginia",
  "virgin islands",
  "vermont",
  "washington",
  "wisconsin",
  "west virginia",
  "wyoming",
] as const;

/** Two-letter state/territory codes (word-boundary matched). */
export const US_STATE_CODES = [
  "AK",
  "AL",
  "AR",
  "AS",
  "AZ",
  "CA",
  "CO",
  "CT",
  "DC",
  "DE",
  "FL",
  "GA",
  "GU",
  "HI",
  "IA",
  "ID",
  "IL",
  "IN",
  "KS",
  "KY",
  "LA",
  "MA",
  "MD",
  "ME",
  "MI",
  "MN",
  "MO",
  "MP",
  "MS",
  "MT",
  "NC",
  "ND",
  "NE",
  "NH",
  "NJ",
  "NM",
  "NV",
  "NY",
  "OH",
  "OK",
  "OR",
  "PA",
  "PR",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VA",
  "VI",
  "VT",
  "WA",
  "WI",
  "WV",
  "WY",
] as const;

/**
 * Countries/regions OUTSIDE the US. Any of these appearing in a location
 * string (word boundary) marks the role as non-US. Deliberately not
 * exhaustive of the whole planet — it covers the countries the user flagged
 * (UK, Germany, Japan, France, Denmark, Spain, Singapore, Ireland) plus the
 * common international remote hubs.
 */
export const NON_US_REGIONS = [
  "uk",
  "united kingdom",
  "england",
  "scotland",
  "wales",
  "britain",
  "london",
  "manchester",
  "birmingham",
  "edinburgh",
  "germany",
  "berlin",
  "munich",
  "hamburg",
  "frankfurt",
  "cologne",
  "france",
  "paris",
  "lyon",
  "denmark",
  "copenhagen",
  "netherlands",
  "amsterdam",
  "rotterdam",
  "belgium",
  "brussels",
  "switzerland",
  "zurich",
  "austria",
  "vienna",
  "sweden",
  "stockholm",
  "norway",
  "oslo",
  "finland",
  "helsinki",
  "finland",
  "ireland",
  "dublin",
  "cork",
  "spain",
  "madrid",
  "barcelona",
  "portugal",
  "lisbon",
  "italy",
  "milan",
  "italy",
  "japan",
  "tokyo",
  "osaka",
  "kyoto",
  "singapore",
  "hong kong",
  "china",
  "beijing",
  "shanghai",
  "shenzhen",
  "taiwan",
  "taipei",
  "south korea",
  "seoul",
  "india",
  "bengaluru",
  "bangalore",
  "mumbai",
  "delhi",
  "canada",
  "toronto",
  "vancouver",
  "montreal",
  "australia",
  "sydney",
  "melbourne",
  "brisbane",
  "new zealand",
  "auckland",
  "israel",
  "tel aviv",
  "dubai",
  "poland",
  "warsaw",
  "krakow",
  "czech",
  "prague",
  "romania",
  "bulgaria",
  "greece",
  "athens",
  "south america",
  "brazil",
  "sao paulo",
  "mexico",
  "mexico city",
  "argentina",
  "buenos aires",
  "africa",
  "nigeria",
  "kenya",
  "egypt",
  "south africa",
  "capetown",
  "middle east",
  "saudi arabia",
  "united arab emirates",
  "uae",
  "qatar",
  "india",
] as const;

/**
 * Early-career markers. A title containing any of these, or an explicit
 * experience requirement of at most MAX_EXPERIENCE_YEARS, puts the role in
 * scope. Scope is internships/co-ops, full-time new-grad / early-career
 * (0-2 YoE), AND part-time software roles (2026-08-21 user addition:
 * "everything and anything part-time software engineering", incl.
 * hours-based phrasing like "15-20 hours").
 */
export const EARLY_CAREER_MARKERS = [
  "intern",
  "internship",
  "co-op",
  "coop",
  "apprentice",
  "apprenticeship",
  "work study",
  "work-study",
  "new grad",
  "new graduate",
  "early career",
  "entry level",
  "entry-level",
  "recent grad",
  "graduate",
  "university",
  "undergrad",
  "fresh grad",
  "campus",
  "summer associate",
  "junior",
  "jr.",
  "new hire",
  "student",
  "software engineer i",
  "software engineer 1",
  "developer i",
  "developer 1",
  "swe i",
  "swe 1",
  "engineer i",
  "engineer 1",
  "level i",
  "level 1",
  "l1",
  "l3",
  // Part-time is its own early-career lane (2026-08-21): "Part-Time Software
  // Developer" carries no intern marker but is exactly the target realm.
  "part-time",
  "part time",
] as const;

/**
 * Hours-per-week phrasing that conveys part-time ("15-20 hours", "20 hrs per
 * week"). Matched by regex in the engine, capped at FULL_TIME_MAX_WEEK_HOURS.
 */
export const FULL_TIME_MAX_WEEK_HOURS = 35;

/** Hard cap on stated years-of-experience requirements (0-2 YoE allowed). */
export const MAX_EXPERIENCE_YEARS = 2;

/**
 * Seniority / leadership markers that put a role out of early-career scope.
 * Matched on the TITLE only (prose mentioning senior people inside the
 * description must never suppress an internship).
 */
export const SENIORITY_MARKERS = [
  "senior",
  "sr.",
  "sr",
  "staff",
  "principal",
  "lead",
  "leader",
  "leadership",
  "manager",
  "director",
  "vp",
  "vice president",
  "head of",
  "head",
  "architect",
  "distinguished",
  "fellow",
  "expert",
  "experienced",
  "ii",
  "iii",
  "iv",
  "v",
  "senior staff",
] as const;

/**
 * Engineering DISCIPLINES that are not software/data/ML engineering. These
 * WIN over the generic "engineer" marker: a "Bridge Engineer" or "Process
 * Engineer Intern" carries "engineer" but is a different discipline entirely
 * (2026-08-21: "Entry-Level Bridge Engineer" alerted at 70%). Explicitly
 * software markers ("Software Engineer", "Data Engineer") still win over
 * these via the software-signal check.
 */
export const NON_SOFTWARE_DISCIPLINES = [
  "civil",
  "structural",
  "bridge",
  "highway",
  "mechanical",
  "electrical",
  // Hardware EE is out; embedded SOFTWARE stays reachable via
  // "embedded software"/"firmware" software markers.
  "electronics",
  "aerospace",
  "aeronautical",
  "chemical",
  "process engineer",
  "process intern",
  "manufacturing",
  "industrial engineer",
  "field service",
  "field technician",
  "maintenance",
  "hvac",
  "plumbing",
  "petroleum",
  "materials engineer",
  "environmental engineer",
  "agricultural",
  "biomedical engineer",
  "quality engineer",
  "validation engineer",
  "autocad",
  "cad engineer",
  "surveyor",
  "construction",
] as const;

/** Software / data / ML engineering-track role families (positive gate). */
export const ENGINEERING_TRACK_MARKERS = [
  // core SWE
  "software",
  "swe",
  "developer",
  "programmer",
  "engineer",
  "engineering",
  // web / application layers
  "backend",
  "back end",
  "frontend",
  "front end",
  "full-stack",
  "fullstack",
  // data + ML + applied AI
  "data",
  "ml",
  "machine learning",
  "ai",
  "artificial intelligence",
  "nlp",
  // infra / platform / ops
  "infrastructure",
  "infra",
  "platform",
  "systems",
  "sre",
  "devops",
  "cloud",
  // embedded / low-level
  "embedded",
  "firmware",
  // test / automation / reliability of software itself
  "test",
  "testing",
  "qa",
  "quality assurance",
  "automation",
  // developer tooling
  "developer tools",
  "devtools",
  // specialized engineering
  "research engineer",
  "security engineer",
  "quant",
] as const;

/**
 * Explicitly non-software role families. These WIN over engineering-track
 * markers: the user's scope is software + data + ML only, so a "Sales
 * Engineer", "Design Engineer", or "Legal Ops Engineer" is out of scope even
 * though "engineer" appears in the title.
 */
export const NON_ENGINEERING_ROLE_MARKERS = [
  "sales",
  "account executive",
  "account manager",
  "business development",
  "bd",
  "sdr",
  "bdr",
  "marketing",
  "content",
  "brand",
  "growth",
  "seo",
  "design",
  "designer",
  "ux",
  "ui",
  "product designer",
  "product manager",
  "product management",
  "pm",
  "program manager",
  "project manager",
  "recruiter",
  "recruiting",
  "talent",
  "people ops",
  "hr",
  "human resources",
  "operations",
  "ops",
  "compliance",
  "grc",
  "governance",
  "risk",
  "legal",
  "law",
  "paralegal",
  "finance",
  "accounting",
  "controller",
  "customer success",
  "customer support",
  "support engineer (non-technical)",
  // Customer-facing services/field/support ICs. The user's scope is
  // engineering-track SWE/infra — a "Technical Support Engineer", "Solutions
  // Engineer" (presales), "Field Engineer", or "Escalations Engineer" carries
  // "engineer" but is a support/services role, exactly like a Sales Engineer.
  "support engineer",
  "technical support",
  "technical services",
  "technical escalation",
  "escalation engineer",
  "escalations engineer",
  "services engineer",
  "service engineer",
  "solutions engineer",
  "solution engineer",
  "field engineer",
  "customer engineer",
  "network support",
  "client success",
  "community",
  "social media",
  "coordinator",
  "operations associate",
  "implementation",
  "onboarding",
  "solutions consultant",
  "analyst",
  "accountant",
  "auditor",
  "business analyst",
  "data analyst (non-eng)",
  "technical writer",
  "writer",
  "editor",
  "teacher",
  "instructor",
  "administrative",
  "executive assistant",
  "office manager",
  "receptionist",
  // Retail / hospitality / campus-service lanes that kept leaking through
  // generic early-career markers (2026-08-21 alert log): Target posts a
  // "Store Executive Intern (Store Leadership Intern)" per store location;
  // dining halls post "Culinary Service Associate".
  "store",
  "retail",
  "clerk",
  "cashier",
  "culinary",
  "kitchen",
  "barista",
  "server",
  "waiter",
  "hostess",
  "merchandis",
  "warehouse",
  "stocker",
  "forklift",
  "driver",
  "courier",
  "housekeeping",
  "janitorial",
  "facilities",
  "concierge",
  "bellhop",
  "events intern",
  "event intern",
  "hospitality",
  "food service",
  "food safety",
  "dietary",
  "nutrition",
  "resident assistant",
  "athletics",
  "recreation",
  "lifeguard",
  "counselor",
] as const;

/** Skills used to differentiate score (title matches weigh more). */
export const TITLE_STRONG_SKILLS = [
  "python",
  "golang",
  "go",
  "rust",
  "c++",
  "cpp",
  "c#",
  "java",
  "typescript",
  "javascript",
  "react",
  "node",
  "sql",
  "postgres",
  "kubernetes",
  "docker",
  "aws",
  "gcp",
  "azure",
  "pytorch",
  "tensorflow",
  "llm",
  "large language model",
  "genai",
  "rag",
  "distributed",
  "pipeline",
  "etl",
  "data analysis",
] as const;

export const DESCRIPTION_STRONG_SKILLS = [
  "python",
  "golang",
  "rust",
  "c++",
  "java",
  "typescript",
  "javascript",
  "pytorch",
  "tensorflow",
  "kubernetes",
  "docker",
  "postgres",
  "sql",
  "aws",
  "gcp",
  "azure",
  "llm",
  "rag",
  "distributed systems",
  "etl",
] as const;

export interface RelevanceProfile {
  /** Role must be in at least one of these countries (default: US only). */
  allowedCountries: string[];
  /**
   * Minimum explained fit for a within-scope role to be considered alertable.
   * Defaults low (any within-scope role alerts per PRD "ranks don't gate");
   * hard gates already suppress out-of-scope noise.
   */
  alertThreshold: number;
}
